// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCajkTuTJ-MTM3-mLXyvrX8lCCclrpJGDw',
    appId: '1:653618063558:web:099939c50b09ca320ccfc7',
    messagingSenderId: '653618063558',
    projectId: 'carpacking-597b1',
    authDomain: 'carpacking-597b1.firebaseapp.com',
    storageBucket: 'carpacking-597b1.appspot.com',
    measurementId: 'G-E3SPRYD8F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsZ4bmQpYgKKgsmME5fXfXu25Jph5cEX0',
    appId: '1:653618063558:android:671cd57de5f93ede0ccfc7',
    messagingSenderId: '653618063558',
    projectId: 'carpacking-597b1',
    storageBucket: 'carpacking-597b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsfvLtIlGecWYikeAnd0LTM6-Vd9aH4mE',
    appId: '1:653618063558:ios:dc45ae81eda7d51d0ccfc7',
    messagingSenderId: '653618063558',
    projectId: 'carpacking-597b1',
    storageBucket: 'carpacking-597b1.appspot.com',
    iosClientId: '653618063558-k7n8feud8k64nvd50glasdmifle4erpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardscanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsfvLtIlGecWYikeAnd0LTM6-Vd9aH4mE',
    appId: '1:653618063558:ios:dc45ae81eda7d51d0ccfc7',
    messagingSenderId: '653618063558',
    projectId: 'carpacking-597b1',
    storageBucket: 'carpacking-597b1.appspot.com',
    iosClientId: '653618063558-k7n8feud8k64nvd50glasdmifle4erpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardscanner',
  );
}
